update emulator test (#263)
* revert test case

* update emulator test

fvm returns additional errors after upgrading, due to preprocessing.

```
[Error Code: 1101] error caused by: 2 errors occurred:
* transaction preprocess failed: [Error Code: 1101] cadence runtime error: Execution failed:
error: authorizer count mismatch for transaction: expected 0, got 1
--> 1ae04fd007e8137d3a433f2248b34770a249f148fcd2405480b2c0076d5129d8

* transaction verification failed: checking frozen account failed: cannot check account freeze status: [Error Code: 1201] account not found for address 01cf0e2f2f715450
```

Co-authored-by: Bastian Müller <bastian@axiomzen.co>